class DuckDBPyConnection:
    description: list[tuple[str, object, object, object, object, object, object]]
    def execute(
        self,
        query: str,
        parameters: object | None = None,
    ) -> DuckDBPyConnection: ...
    def fetchone(self) -> tuple[object, ...] | None: ...
    def fetchall(self) -> list[tuple[object, ...]]: ...
    def close(self) -> None: ...

def connect(database: str, *, read_only: bool = False) -> DuckDBPyConnection: ...
