from collections.abc import Iterable, Iterator, Mapping
from pathlib import Path
from typing import TypeVar, overload

_T = TypeVar("_T")

class ConfigValue(str):
    def __iter__(self) -> Iterator[object]: ...
    def __getattr__(self, name: str) -> ConfigValue: ...
    @overload
    def get(self, key: str) -> object: ...
    @overload
    def get(self, key: str, default: _T) -> _T: ...

class DictConfig(Mapping[str, object]):
    def __getitem__(self, key: str) -> ConfigValue: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __getattr__(self, name: str) -> ConfigValue: ...
    @overload
    def get(self, key: str) -> object: ...
    @overload
    def get(self, key: str, default: _T) -> _T: ...
    def items(self) -> Iterable[tuple[str, object]]: ...

class ListConfig(list[object]):
    def __getattr__(self, name: str) -> ConfigValue: ...

class OmegaConf:
    @staticmethod
    def load(path: str | Path) -> DictConfig: ...
    @staticmethod
    def merge(*configs: object) -> DictConfig: ...
    @staticmethod
    def to_container(config: object, *, resolve: bool = ...) -> object: ...
    @staticmethod
    @overload
    def select(config: object, key: str) -> object: ...
    @staticmethod
    @overload
    def select(config: object, key: str, default: _T) -> _T: ...
