from collections.abc import Iterator
from typing import Self

class _DynamicValue:
    def __call__(self, *args: object, **kwargs: object) -> _DynamicValue: ...
    def __iter__(self) -> Iterator[str]: ...
    def __getitem__(self, key: object) -> _DynamicValue: ...
    def __contains__(self, item: object) -> bool: ...
    def __bool__(self) -> bool: ...
    def read(self, size: int = -1) -> bytes: ...
    def decode(self, encoding: str = "utf-8", errors: str = "strict") -> str: ...
    def __getattr__(self, name: str) -> _DynamicValue: ...

class FilePath(str):
    def __new__(cls, path: str, *, file_name: str | None = None) -> Self: ...

class TablePath(str):
    def __new__(
        cls,
        path: str,
        *,
        append: bool = False,
        schema: object | None = None,
    ) -> Self: ...

class Operation:
    id: str

    def wait(self) -> None: ...
    def get_state(self) -> str: ...
    def get_error(self) -> str | None: ...

class TypedJob:
    def __call__(self, row: object) -> object: ...

class YtClient:
    config: dict[str, object]

    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def exists(self, path: str) -> bool: ...
    def row_count(self, path: str) -> int: ...
    def run_operation(self, *args: object, **kwargs: object) -> Operation | None: ...
    def run_query(self, *args: object, **kwargs: object) -> Operation: ...
    def __getattr__(self, name: str) -> _DynamicValue: ...

class MapSpecBuilder:
    def __getattr__(self, name: str) -> _DynamicValue: ...

class VanillaSpecBuilder:
    def __getattr__(self, name: str) -> _DynamicValue: ...

def create(*args: object, **kwargs: object) -> _DynamicValue: ...
def write_file(*args: object, **kwargs: object) -> _DynamicValue: ...
def read_file(*args: object, **kwargs: object) -> _DynamicValue: ...
def exists(path: str) -> bool: ...
def remove(*args: object, **kwargs: object) -> _DynamicValue: ...
def get(*args: object, **kwargs: object) -> _DynamicValue: ...
def run_map(*args: object, **kwargs: object) -> Operation: ...
def run_reduce(*args: object, **kwargs: object) -> Operation: ...
def run_map_reduce(*args: object, **kwargs: object) -> Operation: ...
def run_sort(*args: object, **kwargs: object) -> Operation: ...
def run_merge(*args: object, **kwargs: object) -> Operation: ...
def __getattr__(name: str) -> _DynamicValue: ...
