class TableSchema:
    def __getattr__(self, name: str) -> object: ...

class SortColumn:
    def __init__(self, name: str, *, sort_order: str = "ascending") -> None: ...
    def __getattr__(self, name: str) -> object: ...
